### ISSUE TITLE
Archive dpr-api and related repos under frictionlessdata and move dpr-js here

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#10]
We want to archive dpr-api repos under frictionlessdata to reduce confusion (suggest we move to oki-archive).

Only one to keep is dpr-js and i suggest moving that here (datahq) as frontend-js (or even consider merging into the frontend for now?)

## Tasks

To archive:

* [x] dpr-api
* [x] dpm-py

To migrate

* [x] dpr-js (or merge)

**Comment by rufuspollock** [comment]
@anuveyatsu @zelima i've now archived and leave you to migrate dpr-js (which i suggest we rename to frontend-js - or even just merge into frontend ...)

**Comment by anuveyatsu** [comment]
@rufuspollock  @zelima let's migrate it, not merge it for now..

**Comment by rufuspollock** [comment]
FIXED. dpr-js now at https://github.com/datahq/frontend-showcase-js
