### ISSUE TITLE
Meta data in a `flow.yaml`

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/pm#100]
As a user I want to describe my data with minimal efforts.
## Acceptance criteria
* [ ] all the dataset metadata could be defined in the `flow.yaml` meta section

## Analysis
When user automates a dataset he should create `.datahub/flow.yaml` file, which has a meta section:
```yaml
meta:
  dataset: gdp
  findability: public
```
but also user should create a `.datahub/datapackage.json` file and put some metadata there as well, otherwise description will not appear on the datahub page after processing.
```json
{
  "name": "gdp",
  "title": "Country, Regional and ...",
  "description": "Country, regional and ...",
  "readme": "Country, regional and ...",
  "license": "PDDL-1.0",
```
This doubling is obviously redundant and confusing.

Before we used `.datahub/datapackage.json` to define the resource schema, but now it could be done in the `flow.yaml` file, or auto-inferred from the remote source: https://github.com/datahq/datahub-client/issues/10

**Comment by zelima** [comment]
WONTIFX it's just a small effort from user's perspective and quite big refactors.
