### ISSUE TITLE
[blog] post about embeddable views and HTML tables for resources

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#125]
Since we've implemented a feature to share and embed views and resource tables from Datahub, we want to write a blog post about it so users get informed about new functionalities.

## Acceptance criteria

* [ ] a blog post about it at https://datahub.io/blog/

## Tasks

* [ ] draft
* [ ] review
* [ ] refactor
* [ ] publish

**Comment by AcckiyGerman** [comment]
Fixed here: https://github.com/datahq/pm/issues/128
http://datahub.io/blog/new-datahub-features-and-improvements

**Comment by zelima** [comment]
@AcckiyGerman can you close if fixed? also, that link 404s
