### ISSUE TITLE
URI or not URI

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/pm#126]
The PY and JS versions of the `tableschema` lib are treating the raw **IPv4** address in a different way:
- JS thinks it is URI
- PY thinks it isn't

Because of that, we have plenty of bugs, when JS version infers the schema, which is treated as incorrect while processing.

We had created issues in the frictionlessdata:
https://github.com/frictionlessdata/tableschema-py/issues/204
https://github.com/frictionlessdata/tableschema-js/issues/135
But their developers seems too busy atm, so I'm gonna make a PR to solve this.

## Tasks

- [ ] make PY and JS version of tableschema consistent

## Analysis

Dima German @AcckiyGerman 11:08
@anuveyatsu @zelima @akariv I could either

- Require URI schema in tableschema-JS (that means 8.8.8.8 is not URL)
- Don't require URI schema in tableschema-PY (that means 8.8.8.8 is an URL)
Both variants would work.
So what would be the decision? Should I ask in Frictionless data chat one more time about if the IP is a URL?

Anuar Ustayev @anuveyatsu 11:09
@AcckiyGerman From 19th February on FD channel:

> Hi all, do you think IP addresses should be considered as URI or not? E.g., ”9.196.147.78” value is a string type and uri format.
> @anuveyatsu an IP address is not a URI.

Dima German @AcckiyGerman 11:10
I'd like to see if everybody is agree with that

Adam Kariv @akariv 11:10
@AcckiyGerman my opinion is that 8.8.8.8 is not a url.
https://8.8.8.8/ is

Dima German @AcckiyGerman 11:11
Ok, cool, preparing a PR, if nobody objects

**Comment by zelima** [comment]
@AcckiyGerman very good question to answer, but unfortunately something that we can not decide :)
> First, let's decide, is 8.8.8.8 is URI, or not... lurking docs..

**Comment by AcckiyGerman** [comment]
@zelima The `validator` JS lib, has a method `isURL()` , which is used in `tableschema-js`
`isURL()` could have an option `isURL(..., {require_protocol: true})` which will treat all usual IP as non-valid URL. I think this could help. Let me check, how is this realised in `tableschema-PY`, may be there is an options to Allow validation of pure IP as URL

**Comment by AcckiyGerman** [comment]
FIXED
URI type is now consistent in `JS` & `PY` versions of `tableschema` and some raw IP without schema address is not URI type for us any more :)

- `Infer()` method will treat value `8.8.8.8` as a **String with type Default**
- Validator changed its behavior accordingly.
