### ISSUE TITLE
Comparison - Sendgrid and Mailchimp

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/pm#145]
## User Stories 
* As Datahub developer, i want to send transaction emails, so users can receive updates about welcome signup, other account activity.
* As Open-Revolution developer, i want to send download emails, so users can download the book.
* As Open-Revolution developer, i want to send promotional emails, so users can stay connected to the idea.

##### Pros
* Strong API support for transnational emails 
* Emails land in gmail primary tab  [tested]

#### Cons
* Not so good for promotional emails
* No integration without API
* No automated emails without API
* Comes for a monthly Price

#### Price
* Send up to 40,000 emails free for 30 days, then send 100 emails/day free forever
* Send around 40,000 emails per month From 9.95/mo

#### Pros
* Easy to use and GUI based
* Fast and plenty online editing options
* Automated Emails(like send download link to new subscriber) and Signup Forms without relying on API, Makes basic integration easier and faster
* Affordable

#### Cons
* Emails dropping in Promotions Tabs

#### Price
* Forever Free Up to 2,000 subscribers and 12,000 emails per month

**Comment by zelima** [comment]
@tanvirchahal Personally I think that MailChimp still remains the best option here. It's free, automated, easy to use etc... think "Emails dropping in Promotions Tabs" Is not enough benefit to move to Sendgrid. 

Also looking at the stats of the MailChimp we have quite big open rate:

* Average open rate is > 53%
* Average click rate is > 13%

**Comment by tanvirchahal** [comment]
I agree @zelima, mailchimp offers a lot more and being free at the same time.

**Comment by zelima** [comment]
@tanvirchahal great, can you close this as FIXED and indicate the time you've spent on research as an estimate

**Comment by tanvirchahal** [comment]
2:30h

**Comment by rufuspollock** [comment]
@tanvirchahal can i suggest we get this comparison into a spreadsheet and get pricing info for mailchimp for say emails to 10,000 people a month ... (even if we do have a decision).

**Comment by tanvirchahal** [comment]
[email-services-comparison.xlsx](https://github.com/datahq/pm/files/1964752/email-services-comparison.xlsx)

Price Comparison between Sendgrid, Mailchimp and Amazon.  Each of them has a different payment structure, thus kept in different sheets.

**Comment by tanvirchahal** [comment]
Moved to the doc listed above @zelima
