### ISSUE TITLE
Misc things to think about 2017-08-28

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#15]
This is a backlog of questions to chat about ...

* [ ] Aliasing data urls and have a uuid internally or similar (why? well it makes sense for data files that don't have a name anyway, provides pseudo undiscoverability, allows relocation later easier)
  * Would require an aliasing setup (which we already sort of have)
* [ ] talk with @akariv about how we handle api keys so that people can push over the API (at the moment you get the API key via logging in and it expires at some point ... - maybe you renew ..)
  * As a Developer I want to push things into DataHub over the API without manual intervention so that I can automate this process
* [x] Why `dervied/csv` but `source/tabular` in datahub/type
* [x] BIG - need a way to do deployments that don't "break" the site as we had with pipelines upgrade. How can we do this? One idea: separate builds to master which deploy on testing from deployments to a special production branch which deploy on production.

**Comment by rufuspollock** [comment]
> need a way to do deployments that don't "break" the site as we had with pipelines upgrade. How can we do this? One idea: separate builds to master which deploy on testing from deployments to a special production branch which deploy on production.

We fixed this.

**Comment by zelima** [comment]
FIXED/OBSOLETE 

UUID of the dataset is "similar"  with URL: 
* URL may look like this `https://datahub.io/owner-name/dataset-name` Eg https://datahub.io/core/finance-vix
* UUID of the dataset may look like this `owner-id/dataset-name` Eg: core/finance-vix or `81429fdgdfgdb180f54c142fac32f83b/finance-vix`
