### ISSUE TITLE
Blog post for world bank datasets

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#194]
As the DataHub team, we want to create a blog post for world-bank datasets so that people from the community and our followers on social networks aware of those new datasets on datahub.

## Acceptance criteria

- [x] Blog post on the datahub

## Tasks

- [x] Create a blog post describing datasets on world-bank
- [x] publish it

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/world-bank-indicators-on-datahub
