### ISSUE TITLE
dpp-runner is not removing temp directory after processing is done 

### ISSUE THREAD

**Issue by zelima** [datahq/pm#215]
Originally coming from https://github.com/datahq/pm/issues/197

After analyzing the cluster performance we discovered that disc usage is constantly increasing that is probably related to the fact that dpp-runner is not deleting temp dir after processing data. This leads in specstore hanging when it is processing big data

## Acceptance Criteria

* [ ] We don't hit the critical point of disk usage

## Tasks

* [ ] Investigate reason
* [ ] Fix

## Analysis

Here you can see the disk space usage is constantly going up until servcie is redeployed for various reasons. 

![gke container - disk usage for datahub-production](https://user-images.githubusercontent.com/15143785/42748270-9aa92628-88f0-11e8-989d-345c29ef11b8.png)

This makes me thinkg that we are saving stuff on the disc an never deleting for some reasons. Eg processing of this dataset crashed due to memory lack: https://api.datahub.io/source/sports-data/atp-world-tour-tennis-data/2

See detailed analysis here https://github.com/datahq/pm/issues/197#issuecomment-405476490

**Comment by zelima** [comment]
@akariv did you have a chance to take a look at this issue? Since I increased the total disc space it got rare but, at some point we are facing every once in a while. Specstore disk space usage shown below: 

![image](https://user-images.githubusercontent.com/15143785/45197543-f3bbff00-b272-11e8-9ce2-4407df7790a1.png)

**Comment by akariv** [comment]
@zelima can you please take a look and lmk what you think -
https://github.com/akariv/dpp-runner/pull/1

**Comment by zelima** [comment]
@akariv Yes, think it should solve :+1:

**Comment by zelima** [comment]
FIXED This should not be a problem any more

**Comment by zelima** [comment]
Actually, this still is an issue. Probably  this is still not merged https://github.com/akariv/dpp-runner/pull/1
