### ISSUE TITLE
Pushing files with extension .arff bug

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/pm#243]
When uploading files to datahub, files with an extension .arff are not processed. Examples of arff files can be found at https://www.openml.org/search?type=data

## Acceptance criteria

- [x] When the user pushes files to datahub, files with extension .arff should also be visible next to csv, json and zip files

## Tasks

* [x] Do analysis
* [x] Fix if processing Bug

## Analysis

TODO

**Comment by zelima** [comment]
@Branko-Dj I'd like to see examples from datahub or GitHub (processed ones). Where can I find them?

**Comment by zelima** [comment]
Here's one of them https://api.datahub.io/source/machine-learning/arrhythmia/successful

**Comment by zelima** [comment]
OK, this took me a while, but finally got it. @Branko-Dj The reasons they are not getting there are:

1. There is **no** `.arff` resource added to the resource list in dp.json Eg: This one has only 1 resource init and it's CSV https://api.datahub.io/source/machine-learning/hepatitis/successful
  1.1. Also aside, but something wrong with resource `path`
2. The is `.arff` resource in resouce list, but it has the same exact name as the CSV resource. In the background it's just getting overwritten. Eg https://api.datahub.io/source/machine-learning/arrhythmia/successful

So solution is following:

1. Add the `.arff` to the reource list
2. rename resource to Eg `arrhythmia_arff`

**Comment by Branko-Dj** [comment]
Arff resources were renamed with `_arff ` added to the file name. After reinitializing the datapackage and repushing to datahub the issue was resolved
