### ISSUE TITLE
Assembler/pipeline bugs

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#30]
In this issue, we will accumulate bugs from assembler/pipelines.

## Wrong error logs from source API

1. I push some dataset with wrong schema
2. pipeline for derived/csv fails showing nice error about wrong schema
3. but the “main” pipeline fails due to `Dirty dependency` error so status API gives me that error, which is not helpful.

E.g., http://api.datahub.io/source/90998f7f90e086bd5fc7c9075dfda43b/sample-simple-itchy-starfish-27/info

## Processing Excel file's sheet

When I want to process a sheet other than 1st one, `derived` versions not working - https://datahub.io/anuveyatsu/sample-simple-rotten-snake-18 . See source spec here - https://api.datahub.io/source/90998f7f90e086bd5fc7c9075dfda43b/sample-simple-rotten-snake-18/info . I am including schema for this 2nd sheet withing Excel resource.

**Comment by akariv** [comment]
Wrong error logs -> should be resolved with commit https://github.com/frictionlessdata/datapackage-pipelines/commit/d683d5171a8ad7d735698d7a3fad2aa19ccd3d38 on `datapackage-pipelines`

**Comment by akariv** [comment]
Processing Excel file's sheets -> should be resolved with commit  https://github.com/datahq/assembler/commit/56f2154619a7b3ba4a97ae7beffa1d8863a93b84 of `assember`
@anuveyatsu please reopen in case this doesn't work.
