### ISSUE TITLE
Garbage collection for rawstore

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#4]
Situation: I push a data package but there is something wrong with it. I push again and it works. I now have an old broken data package sitting in rawstore and an obsolete pipeline pointing to it.

**Comment by akariv** [comment]
Obsolete pipeline - only if the two datasets have different names.
Assuming the user has a limited quota, I see no harm in letting her manage
faulty uploads and delete unwanted pipelines and files.

**Comment by rufuspollock** [comment]
@akariv agree. This is a placeholder issue for thinking about this so please comment.

**Comment by rufuspollock** [comment]
FIXED. The new factory system using content hashes essentially resolves this.
