### ISSUE TITLE
Blog post about downloading dataset in sqlite format

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#40]
Since we've implemented generating sqlite format for the datasets, we want to create a blog post about it.

## Acceptance criteria

* [ ] published blog post about datasets in sqlite format at https://datahub.io/blog/download-dataset-in-sqlite

## Tasks

* [ ] write blog post about sqlite versions
  * [ ] review
  * [ ] publish

**Comment by zelima** [comment]
WONTFIX not on the roadmap
