### ISSUE TITLE
building graph has a bug, probably it is related to render.js code 

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#45]
When the type is `year`, it somehow converts it into percentage on the showcase page: 
Plelase, see https://datahub.io/core/employment-us. 
In first graph `US population, total employment and unemployment since 1940`, the X axis has a wrong data. For example `195000%` instead of `1950`.
Also, in `preview table`, `year` column has weird order: `1955, 1957, 1956`, which has an impact on the second graph.
Original source seems ok, see https://github.com/datasets/employment-us/blob/master/data/aat1.csv

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/datapackage-render-js/commit/c25b089db6540f3ad53323db0d7afc1caf22020e
