### ISSUE TITLE
Blog post about core datasets

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#48]
We want to have a blog post about core datasets explaining what it is with examples and features provided by datahub.

## Acceptance criteria 

* [ ] published blog post about core datasets on http://datahub.io/blog/core-data-essential-datasets-for-data-wranglers-and-data-scientists

## Tasks

* [x] plan out
* [x] write
* [x] review
* [x] publish

**Comment by anuveyatsu** [comment]
FIXED, see online - http://datahub.io/blog/core-data-essential-datasets-for-data-wranglers-and-data-scientists
