### ISSUE TITLE
Issues re new factory

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#57]
I was testing out new factory, which is now deployed at testing environment - testing.datahub.io -
 and here is some issues we've discovered so far:

* [x] Pipelines are succeeded but metadata is not updated. This is the major problem we're facing right now:
https://testing.datahub.io/anuar.ustayev/co2-ppm
https://testing.datahub.io/anuar.ustayev/vega-views-tutorial-grouping
https://testing.datahub.io/anuar.ustayev/vega-views-tutorial-lines
* [x] Pipelines are succeeded but zip versions not working:
https://testing.datahub.io/anuar.ustayev/finance-vix
https://testing.datahub.io/anuar.ustayev/geojson-tutorial
https://testing.datahub.io/anuar.ustayev/vega-views-tutorial-grouping
* [x] Also, as I understand, if pipelines are succeeded they should be removed from pipelines dashboard. However, there are number of them still remaining there for some reason and their status in DB is `pending`:
http://api-testing.datahub.io/pipelines/
* [x] Datasets are duplicated in metastore
https://testing.datahub.io/anuar.ustayev

**Comment by zelima** [comment]
FIXED
