### ISSUE TITLE
bug - datasets are not available from datasets page

### ISSUE THREAD

**Issue by OriHoch** [datahq/pm#82]
## reproduction
* http://datahub.io/
* click on `datasets` in header
* http://datahub.io/search
* click on any dataset
* e.g. the first one `Vega Graph Spec Tutorial - Yields of Barley`
* http://datahub.io/zelima1/vega-views-tutorial-grouping

#### expected
* see the dataset

#### actual
![image](https://user-images.githubusercontent.com/1198854/34334333-377912b2-e94e-11e7-9f4e-88f6359e4224.png)

**Comment by anuveyatsu** [comment]
@OriHoch this is the important one and we're working on it - thank you for reporting!

Meanwhile, could you please open issues in https://github.com/datahubio/qa/issues so more users can see and track the issues.
