### ISSUE TITLE
bug - datapackage.json not available

### ISSUE THREAD

**Issue by OriHoch** [datahq/pm#83]
## reproduction
* http://datahub.io/core/co2-ppm
* scroll to bottom
* click on `datapackage.json`

#### expected
* download the datapackage json

#### actual
![image](https://user-images.githubusercontent.com/1198854/34334380-c0596ed8-e94e-11e7-80a9-48d85d37254f.png)

**Comment by anuveyatsu** [comment]
Thank you for reporting, this should be fixed with next deployment (today/tomorrow).
