### ISSUE TITLE
Add "find/replace" functionality in the pipeliens

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/pm#98]
Currently, I cannot clean my data, it would be very useful if we had find/replace functionality. For example, some data in column Year needs to be cleaned: `2013 (39)` => `2013`.

As a Publisher, I want to be able clean my data so I can normalize values using DataHub system.

## Tasks

* [x] processor for find/replace in dpp https://github.com/frictionlessdata/datapackage-pipelines/issues/114

**Comment by zelima** [comment]
FIXED in https://github.com/frictionlessdata/datapackage-pipelines/issues/114
